#pragma once

#ifdef USE_PIX

#include <Windows.h>
#include <pix3.h>

#define PROFILER_COLOR_BLACK PIX_COLOR(0, 0, 0)
#define PROFILER_COLOR_RED PIX_COLOR(255, 0, 0)
#define PROFILER_COLOR_GREEN PIX_COLOR(0, 255, 0)
#define PROFILER_COLOR_BLUE PIX_COLOR(0, 0, 255)
#define PROFILER_COLOR_WHITE PIX_COLOR(255, 255, 255)
#define PROFILER_COLOR_CYAN PIX_COLOR(43, 255, 255)
#define PROFILER_COLOR_PURPLE PIX_COLOR(128, 0, 128)
#define PROFILER_COLOR_ORANGE PIX_COLOR(255, 128, 0)
#define PROFILER_COLOR_YELLOW PIX_COLOR(255, 255, 0)
#define PROFILER_COLOR_PINK PIX_COLOR(255, 192, 203)
#define PROFILER_COLOR_BROWN PIX_COLOR(128, 0, 0)

#define PROFILER_EVENT_BEGIN(color, ...) PIXBeginEvent(color, __VA_ARGS__)
#define PROFILER_EVENT_END() PIXEndEvent()

#else

#define PROFILER_COLOR_BLACK
#define PROFILER_COLOR_RED
#define PROFILER_COLOR_GREEN
#define PROFILER_COLOR_BLUE
#define PROFILER_COLOR_WHITE
#define PROFILER_COLOR_CYAN
#define PROFILER_COLOR_PURPLE
#define PROFILER_COLOR_ORANGE
#define PROFILER_COLOR_YELLOW
#define PROFILER_COLOR_PINK
#define PROFILER_COLOR_BROWN

#define PROFILER_EVENT_BEGIN(color, ...)
#define PROFILER_EVENT_END()

#endif